{
  programs.glide-browser = {
    enable = true;
    package = null;

    settings = {
      mapleader = " ";
      label_generators = "customLabelGenerators";

      preferences = {
        "browser.tabs.warnOnClose" = false;
      };

      options = {
        native_tabs = "autohide";
        hint_chars = "arst";
      };

      search_engines = [
        {
          name = "Kagi";
          keyword = "k";
          search_url = "https://kagi.com/search";
        }
      ];

      excmds = [
        {
          info = {
            name = "OpenConfig";
            description = "Open the generated config";
          };
          fn = "(ctx) => ctx.open('file:///tmp/glide.ts')";
        }
      ];

      keymaps = [
        {
          modes = "normal";
          key = "gf";
          action = "open_file_picker";
          options.description = "Open a file";
        }
      ];

      autocmds = [
        {
          event = "ConfigLoaded";
          callback = "() => console.log('loaded')";
        }
      ];
    };

    addons = [
      {
        url = "https://example.com/addon.xpi";
        options.force = true;
      }
    ];

    extraConfig = ''
      glide.command_line.open();
    '';

    styles = [
      ''
        body {
          color: red;
        }
      ''
    ];
  };

  nmt.script = ''
    assertFileContent \
      home-files/.config/glide/glide.ts \
      ${builtins.toFile "glide-expected.ts" ''
        /// <reference path="/home/hm-user/.config/glide/glide.d.ts" />
        // Generated by Home Manager.

        glide.g.mapleader = " ";

        glide.hints.label_generators = customLabelGenerators;

        glide.prefs.set("browser.tabs.warnOnClose", false);

        glide.o.hint_chars = "arst";
        glide.o.native_tabs = "autohide";

        glide.search_engines.add({
          keyword: "k",
          name: "Kagi",
          search_url: "https://kagi.com/search"
        });

        glide.excmds.create({
          description: "Open the generated config",
          name: "OpenConfig"
        }, (ctx) => ctx.open('file:///tmp/glide.ts'));

        glide.keymaps.set("normal", "gf", "open_file_picker", {
          description: "Open a file"
        });

        glide.autocmds.create("ConfigLoaded", null, () => console.log('loaded'));

        glide.addons.install("https://example.com/addon.xpi", {
          force: true
        });

        glide.command_line.open();

        glide.styles.add("\n  body {\n    color: red;\n  }");
      ''}
  '';
}
